version: '3'

services:

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: garciawolmerd/node:prod
    container_name: node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: garciawolmerd/nginx-node:prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - '8080:80'

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - node-network
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks:
  node-network:
    name: node-network
    driver: bridge
